# Generated by Django 4.0.6 on 2022-08-15 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thatguide', '0003_user_phone_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='hikingsession',
            name='hike_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiker', to=settings.AUTH_USER_MODEL),
        ),
    ]
