# Generated by Django 4.0.6 on 2022-08-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thatguide', '0003_hikingcheckpoint_checkpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hikingcheckpoint',
            old_name='checkpoint',
            new_name='hike_session',
        ),
    ]
