# Generated by Django 4.0.6 on 2022-08-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thatguide', '0003_hikingcheckpoint_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='hikingsession',
            name='current_elevation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
