# Generated by Django 4.0.6 on 2022-08-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thatguide', '0004_hikingsession_hike_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hikingsession',
            name='distance_list',
        ),
        migrations.AddField(
            model_name='hikingsession',
            name='distance',
            field=models.IntegerField(default=1),
        ),
    ]
