# Generated by Django 4.0.6 on 2022-08-24 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thatguide', '0004_hikingsession_current_elevation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hikingcheckpoint',
            name='time_logged',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
