# Generated by Django 4.0.6 on 2022-08-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thatguide', '0005_hikingcheckpoint_time_logged'),
    ]

    operations = [
        migrations.AddField(
            model_name='hikingsession',
            name='elevation_loss',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
