# Generated by Django 4.0.6 on 2022-08-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thatguide', '0005_remove_hikingsession_distance_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience_list',
            field=models.TextField(blank=True, choices=[('', 'EMPTY'), ('beginner', 'beginner'), ('medium', 'medium'), ('advanced', 'advanced')], default='beginner', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pace_list',
            field=models.TextField(blank=True, choices=[('', 'EMPTY'), ('leisure', 'leisure'), ('powerwalk', 'powerwalk'), ('chased by bear', 'chased by bear')], default='leisure', max_length=15, null=True),
        ),
    ]
