# Generated by Django 4.0.6 on 2022-08-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thatguide', '0006_hikingsession_elevation_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hikingsession',
            name='elevation_gain',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
